name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Version File
        run: |
          echo "export const VERSION_INFO = { version: '1.0.0', commit: '${GITHUB_SHA::7}', date: '$(date -u +"%Y-%m-%d %H:%M:%S UTC")' };" > src/version.js

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create project directory if it doesn't exist
            mkdir -p ~/bakhus
            
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "~/bakhus"
          rm: false

      - name: Restart Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/bakhus
            # Build and restart containers using production compose file
            sudo docker-compose -f docker-compose.prod.yml up -d --build
